/**
 * Centralized cdk-nag suppressions for all stacks.
 *
 * Each suppression documents the reason and whether the finding is:
 *   - ACCEPTED: The current configuration is intentional and appropriate.
 *   - TODO: Should be addressed in a future ticket.
 */
import * as cdk from 'aws-cdk-lib'
import { NagSuppressions } from 'cdk-nag'

const ACCEPTED = 'ACCEPTED'
const TODO = 'TODO'

export function applyNagSuppressions(stack: cdk.Stack): void {
  NagSuppressions.addStackSuppressions(stack, [
    // --- S3 ---
    {
      id: 'AwsSolutions-S1',
      reason: `${TODO}: Enable server access logging on the site bucket.`,
    },
    {
      id: 'AwsSolutions-S10',
      reason: `${TODO}: Enforce HTTPS-only access via aws:SecureTransport condition.`,
    },

    // --- CloudFront ---
    {
      id: 'AwsSolutions-CFR1',
      reason: `${ACCEPTED}: MERMAID is a global marine-data platform; geo restrictions are not appropriate.`,
    },
    {
      id: 'AwsSolutions-CFR2',
      reason: `${TODO}: Evaluate adding AWS WAF integration.`,
    },
    {
      id: 'AwsSolutions-CFR3',
      reason: `${TODO}: Enable CloudFront access logging.`,
    },
    {
      id: 'AwsSolutions-CFR7',
      reason: `${TODO}: Migrate from Origin Access Identity (OAI) to Origin Access Control (OAC).`,
    },

    // --- IAM ---
    {
      id: 'AwsSolutions-IAM4',
      reason: `${ACCEPTED}: AWSLambdaBasicExecutionRole is the standard CDK-managed policy for BucketDeployment Lambda logging.`,
      appliesTo: [
        'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
      ],
    },
    {
      id: 'AwsSolutions-IAM5',
      reason: `${ACCEPTED}: Wildcard actions/resources are generated by CDK BucketDeployment grant helpers; scoped to the specific site bucket and CDK assets bucket. Resource::* is required for CloudFront invalidation APIs (cloudfront:CreateInvalidation, cloudfront:GetInvalidation) which do not support resource-level permissions.`,
      appliesTo: [
        'Action::s3:GetBucket*',
        'Action::s3:GetObject*',
        'Action::s3:List*',
        'Action::s3:Abort*',
        'Action::s3:DeleteObject*',
        'Resource::<StaticSiteBucket9C756C46.Arn>/*',
        {
          regex: '/Resource::arn:aws:s3:::cdk-hnb659fds-assets-.*\\/\\*/',
        },
        'Resource::*',
      ],
    },

    // --- Lambda ---
    {
      id: 'AwsSolutions-L1',
      reason: `${ACCEPTED}: BucketDeployment Lambda runtime is CDK-managed; auto-updated on CDK upgrades.`,
    },
  ])
}
