name: CDK Diff

on: workflow_call

env:
  REACT_APP_AUTH0_DOMAIN: datamermaid.auth0.com
  REACT_APP_MERMAID_REFERENCE_LINK: https://dev-collect.datamermaid.org/#/reference
  REACT_APP_MERMAID_DASHBOARD_LINK: https://dashboard.datamermaid.org
  REACT_APP_CORAL_ATLAS_APP_ID: v8nkxznp3m

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Fetch yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile

      - name: Fetch build cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('src') }}-${{ hashFiles('public') }}

      - name: Yarn Build
        if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        run: yarn build

      # CDK deps
      - name: Fetch cdk node cache
        uses: actions/cache@v3
        id: cdk-cache
        with:
          path: iac/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('iac/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install CDK dependancies
        if: ${{ steps.cdk-cache.outputs.cache-hit != 'true' }}
        working-directory: iac
        run: npm ci

      # Setup TARGET
      - name: Set target for dev
        # if: startsWith(github.base_ref, 'refs/heads/develop')
        run: |
          echo "TARGET=dev" >> "$GITHUB_ENV"
          echo "AUTH0_CLIENT_ID=4AHcVFcwxHb7p1VFB9sFWG52WL7pdNm5" >> "$GITHUB_ENV"
      
      - name: Set target for prod
        if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "TARGET=prod" >> "$GITHUB_ENV"
          echo "AUTH0_CLIENT_ID=XXX" >> "$GITHUB_ENV"

      # - name: CDK Diff
      #   uses: youyo/aws-cdk-github-actions@v2
      #   with:
      #     cdk_subcommand: 'diff'
      #     cdk_args: -c domain=app2.datamermaid.org -c subdomain=${{ env.TARGET }}
      #     actions_comment: true
      #     working_dir: iac
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
      #     CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      #     AWS_DEFAULT_REGION: 'us-east-1'
      #     GITHUB_TOKEN: ${{ github.token }}

      # Diff
      - name: CDK Diff
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CDK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CDK }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          # 
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          # 
          REACT_APP_MERMAID_API: https://"${{ env.TARGET }}".api2.datamermaid.org/v1
          REACT_APP_AUTH0_AUDIENCE: https://"${{ env.TARGET }}"-api.datamermaid.org
          REACT_APP_AUTH0_CLIENT_ID: "${{ env.AUTH0_CLIENT_ID }}"
        working-directory: iac
        run: |
          cdk diff -c domain=app2.datamermaid.org -c subdomain=${{ env.TARGET }}

# ./cdk_diff.sh
