name: 🧪 Test

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub environment to pull secrets from'
        required: true
        type: string
    secrets:
      VITE_AUTH0_CLIENT_ID:
        required: true
      VITE_MAPBOX_ACCESS_TOKEN:
        required: true

jobs:
  test-app:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      VITE_AUTH0_AUDIENCE: ${{ vars.VITE_AUTH0_AUDIENCE }}
      VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
      VITE_AUTH0_DOMAIN: ${{ vars.VITE_AUTH0_DOMAIN }}
      VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}
      VITE_MERMAID_API: ${{ vars.VITE_MERMAID_API }}
      VITE_MERMAID_REFERENCE_LINK: ${{ vars.VITE_MERMAID_REFERENCE_LINK }}
      VITE_MERMAID_EXPLORE_LINK: ${{ vars.VITE_MERMAID_EXPLORE_LINK }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: yarn install --immutable

      - name: Run app tests
        run: TZ=UTC yarn vitest run

  test-storybook:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      VITE_AUTH0_AUDIENCE: ${{ vars.VITE_AUTH0_AUDIENCE }}
      VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
      VITE_AUTH0_DOMAIN: ${{ vars.VITE_AUTH0_DOMAIN }}
      VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}
      VITE_MERMAID_API: ${{ vars.VITE_MERMAID_API }}
      VITE_MERMAID_REFERENCE_LINK: ${{ vars.VITE_MERMAID_REFERENCE_LINK }}
      VITE_MERMAID_EXPLORE_LINK: ${{ vars.VITE_MERMAID_EXPLORE_LINK }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: '.nvmrc'

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: yarn install --immutable

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}
        run: yarn playwright install chromium --with-deps

      - name: Install Playwright OS dependencies
        if: ${{ steps.playwright-cache.outputs.cache-hit == 'true' }}
        run: yarn playwright install-deps chromium

      - name: Run storybook tests
        run: TZ=UTC yarn vitest run --config vitest.storybook.config.ts
